site_name: Timoni
site_description: |
  Timoni is a package manager for Kubernetes powered by CUE lang.
site_author: Stefan Prodan
site_url: https://timoni.sh
repo_name: stefanprodan/timoni
repo_url: https://github.com/stefanprodan/timoni
edit_uri: ""

theme:
  name: material
  logo: images/logo.svg
  favicon: images/favicon.png
  language: en
  custom_dir: docs/theme/
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.top

docs_dir: docs

plugins:
  - search
  - redirects:
      redirect_maps:
        'module-semver.md': 'module-distribution.md'
        'bundles.md': 'bundle.md'

markdown_extensions:
  - attr_list
  - admonition
  - meta
  - codehilite
  - pymdownx.tilde
  - pymdownx.progressbar
  - pymdownx.tasklist
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Introduction: index.md
  - Installation: install.md
  - Quickstart: quickstart.md
  - Topics:
      - Bundle files: bundle.md
      - Bundle runtime: bundle-runtime.md
      - Bundle distribution: bundle-distribution.md
      - Module structure: module.md
      - Module distribution: module-distribution.md
      - Module signing: module-sign.md
      - Values files: values.md
      - Compared to other tools: comparison.md
  - Automation:
      - GitHub Actions: github-actions.md
      - GitOps with Flux: gitops-flux.md
  - Command Reference:
      - Modules:
          - Init: cmd/timoni_mod_init.md
          - Push: cmd/timoni_mod_push.md
          - Pull: cmd/timoni_mod_pull.md
          - List: cmd/timoni_mod_list.md
          - Vet: cmd/timoni_mod_vet.md
          - Vendor Kubernetes APIs: cmd/timoni_mod_vendor_k8s.md
          - Vendor Kubernetes CRDs: cmd/timoni_mod_vendor_crd.md
      - Instances:
          - Apply: cmd/timoni_apply.md
          - Build: cmd/timoni_build.md
          - Delete: cmd/timoni_delete.md
          - List: cmd/timoni_list.md
          - Inspect Module: cmd/timoni_inspect_module.md
          - Inspect Values: cmd/timoni_inspect_values.md
          - Inspect Resources: cmd/timoni_inspect_resources.md
          - Status: cmd/timoni_status.md
      - Bundles:
          - Apply: cmd/timoni_bundle_apply.md
          - Build: cmd/timoni_bundle_build.md
          - Delete: cmd/timoni_bundle_delete.md
          - Lint: cmd/timoni_bundle_lint.md
          - Status: cmd/timoni_bundle_status.md
      - Registries:
          - Login: cmd/timoni_registry_login.md
          - Logout: cmd/timoni_registry_logout.md
      - Artifacts:
          - Push: cmd/timoni_artifact_push.md
          - Pull: cmd/timoni_artifact_pull.md
          - List: cmd/timoni_artifact_list.md
      - Completion:
          - Bash: cmd/timoni_completion_bash.md
          - Fish: cmd/timoni_completion_fish.md
          - Powershell: cmd/timoni_completion_powershell.md
          - ZSH: cmd/timoni_completion_zsh.md
