name: docs

on:
  workflow_dispatch:
  push:
    branches: [ 'docs*' ]
    tags: [ 'v*' ]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Setup Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Generate cmd docs
        run: make prep-docs
      - name: Run mkdocs
        uses: mhausenblas/mkdocs-deploy-gh-pages@55d676092a2f2a3bf0420a1e2ac070868e29f5bc # master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN: timoni.sh
          CONFIG_FILE: mkdocs.yml
          REQUIREMENTS: hack/mkdocs/requirements.txt
