name: e2e

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  kubernetes:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: 1.22.x
          cache-dependency-path: |
            **/go.sum
            **/go.mod
      - name: Setup Kubernetes
        uses: helm/kind-action@99576bfa6ddf9a8e612d83b513da5a75875caced # v1.9.0
        with:
          version: v0.20.0
          node_image: kindest/node:v1.28.0
          cluster_name: kind
      - name: Install
        run: make install
      - name: Push module
        run: |
          timoni mod push ./examples/minimal oci://localhost:5000/minimal -v 1.0.0 --latest
      - name: Install module
        run: |
          timoni -n test apply nginx oci://localhost:5000/minimal
      - name: List modules
        run: |
          timoni list -A
      - name: Upgrade module with custom values
        run: |
          echo 'values: message: "e2e"' | timoni -n test apply nginx oci://localhost:5000/minimal -v 1.0.0 -f-
      - name: Upgrade module with debug values
        run: |
          timoni -n test apply nginx oci://localhost:5000/minimal -f ./examples/minimal/debug_values.cue
      - name: Inspect module
        run: |
          timoni -n test inspect resources nginx
          timoni -n test inspect module nginx
          timoni -n test inspect values nginx
      - name: Status module
        run: |
          timoni -n test status nginx
      - name: Uninstall module
        run: |
          timoni -n test delete nginx --wait
