name: push

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'semver'
        required: true

permissions:
  contents: read

jobs:
  push-minimal:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Setup Cosign
        uses: sigstore/cosign-installer@11086d25041f77fe8fe7b9ea4e48e3b9192b8f19 # v3.1.2
      - name: Setup Timoni
        uses: ./actions/setup
      - name: Login to GHCR
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push and Sign
        run: |
          timoni mod push ./examples/minimal oci://ghcr.io/stefanprodan/timoni/minimal \
          --sign cosign \
          --version ${{ github.event.inputs.version }} \
          -a 'org.opencontainers.image.licenses=Apache-2.0' \
          -a 'org.opencontainers.image.source=https://github.com/stefanprodan/timoni/tree/main/examples/minimal'  \
          -a 'org.opencontainers.image.description=A minimal timoni.sh module example.' \
          -a 'org.opencontainers.image.documentation=https://github.com/stefanprodan/timoni/blob/main/examples/minimal/README.md'
