name: push-artifacts

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'RC version'
        required: true

permissions:
  contents: read

jobs:
  push-minimal:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup Cosign
        uses: sigstore/cosign-installer@11086d25041f77fe8fe7b9ea4e48e3b9192b8f19 # v3.1.2
      - name: Setup Timoni
        uses: ./actions/setup
      - name: Login to GHCR
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push minimal module
        run: |
          timoni mod push ./examples/minimal oci://ghcr.io/stefanprodan/timoni/minimal \
          -v ${{ github.event.inputs.version }} --latest \
          -a 'org.opencontainers.image.licenses=Apache-2.0' \
          -a 'org.opencontainers.image.source=https://github.com/stefanprodan/timoni' \
          -a 'org.opencontainers.image.description=A minimal timoni.sh module.' \
          -a 'org.opencontainers.image.documentation=https://timoni.sh' \
          --sign cosign
      - name: Push schemas
        run: |
          timoni artifact push oci://ghcr.io/stefanprodan/timoni/schemas \
          -f ./schemas -t ${{ github.event.inputs.version }} -t latest \
          -a 'org.opencontainers.image.licenses=Apache-2.0' \
          -a 'org.opencontainers.image.source=https://github.com/stefanprodan/timoni' \
          -a 'org.opencontainers.image.description=Timoni CUE schemas.' \
          -a 'org.opencontainers.image.documentation=https://timoni.sh' \
          --content-type="cue.mod/pkg" \
          --sign cosign
