name: push

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'semver'
        required: true

permissions:
  contents: read

jobs:
  push-minimal:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - name: Setup Cosign
        uses: sigstore/cosign-installer@11086d25041f77fe8fe7b9ea4e48e3b9192b8f19 # v3.1.2
      - name: Setup Timoni
        uses: ./actions/setup
      - name: Login to GHCR
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push and Sign
        run: |
          timoni mod push ./examples/minimal oci://ghcr.io/stefanprodan/timoni/minimal \
          --sign cosign \
          --version ${{ github.event.inputs.version }} \
          --source https://github.com/stefanprodan/timoni/tree/main/examples/minimal  \
          -a 'org.opencontainers.image.description=A minimal timoni.sh module example.' \
          -a 'org.opencontainers.image.documentation=https://github.com/stefanprodan/timoni/blob/main/examples/minimal/README.md'
